 

@HomePage

Feature: To verify Mapsynq welcome Page 

Scenario: Verify mapsynq title on welcome page
Given user is on Mapsynq welcome page 
Then Verify mapsynq title on welcome page
#Then Verify Search bar on Mapsynq welcome page
#Then Verify Sign in tab on welcome page
#Then verify Register tab on welcome page
#Then Verify Mobile App tab on welcome page 
#Then Verify Galactio tab on welcome page
#Then Verify SG GPS Navigation tab on welcome page 
#Then verify Calender tab on  welcome page
#Then Verify legend tab on welcome page


   

  
 
   
